### ISSUE TITLE
Device type not implemented - Razer Viper Ultimate

### ISSUE THREAD

**Issue by Daggerpov** [z3ntu/RazerGenie#94] opened 2020-09-05 07:07 UTC
![image](https://user-images.githubusercontent.com/53918934/92299938-dc2cb500-ef24-11ea-87fd-816fb6e2aa94.png)

**Comment by Daggerpov** [comment] 2020-09-05 07:07
this is on the latest version of Pop! OS

**Comment by z3ntu** [comment] 2020-09-27 11:38
Closing as duplicate of #10

**Closed by z3ntu** 2020-09-27 11:38 UTC
Labels: customeditor, duplicate
