### ISSUE TITLE
The fallback layout should be the system's language

### ISSUE THREAD

**Issue by tildearrow** [z3ntu/RazerGenie#37] opened 2018-12-08 22:57 UTC
Sometimes the getKeyboardLayout() method returns "unknown", and because of this, RazerGenie reports the following warning:
> You are using a keyboard with a layout which is not known to the daemon. Please help us by visiting https://github.com/openrazer/openrazer/wiki/Keyboard-layouts. Using a fallback layout for now.

I have one question, however. Why is the fallback layout the German one?

The best way to get it 90% right is to assume the user's keyboard has his/her language's layout if the layout can't be retrieved, and ultimately, if the language can't be retrieved, then assume English.

**Comment by z3ntu** [comment] 2018-12-09 12:10
I can change the order of fallback languages that will be tried (currently `"de_DE" << "en_US" << "en_GB"`). But imo the fallback language behavior is not really important as unknown languages should be added to the daemon ASAP.
Using the system language would be possible on the master branch, but on the razer_test branch, we don't have "en_US", "en_GB", etc names anymore but string names (see https://github.com/z3ntu/razer_test/blob/master/src/device/razerdevice.h#L121-L131)

**Comment by tildearrow** [comment] 2018-12-09 18:19
> But imo the fallback language behavior is not really important as unknown languages should be added to the daemon ASAP.

The actual problem isn't that the keyboard has an unknown layout, but rather that the keyboard may randomly report an invalid layout...

**Comment by z3ntu** [comment] 2018-12-09 22:09
Then this issue is a duplicate of https://github.com/openrazer/openrazer/issues/525

**Closed by z3ntu** 2018-12-09 22:09 UTC
Labels: enhancement
