### ISSUE TITLE
Device type not implemented - Razer Viper

### ISSUE THREAD

**Issue by sderrico** [z3ntu/RazerGenie#92] opened 2020-08-13 20:29 UTC
Hello,

When I click on `Open Custom Editor` , I get:

`Please open an issue in the RazerGenie repository. Device type: mouse .`

What step I can do to help?

Is there any commands, file to create, etc. ?

Thanks,
Sebastien

**Comment by z3ntu** [comment] 2020-09-27 11:37
Closing as duplicate of #10

**Closed by z3ntu** 2020-09-27 11:37 UTC
Labels: customeditor
