### ISSUE TITLE
Please add Razer Huntsman Elite - matrix 9 22

### ISSUE THREAD

**Issue by lapolis** [z3ntu/RazerGenie#69] opened 2020-03-09 05:59 UTC
When I try to open custom editor it says:
![image](https://user-images.githubusercontent.com/57040859/76186654-eca8e080-61ca-11ea-888b-54d0c5540384.png)

Everything else works. Thanks for your huge contribution.

**Comment by z3ntu** [comment] 2020-03-15 14:25
Closing this as duplicate of #67

**Closed by z3ntu** 2020-03-15 14:25 UTC
