### ISSUE TITLE
Custom Editor Support for Razer Huntsman Elite (de_DE layout)

### ISSUE THREAD

**Issue by Timpsons** [z3ntu/RazerGenie#68] opened 2020-02-19 21:09 UTC
I'd like to use RazerGenie with my Razer Huntsman Elite (German layout de_DE). Trying to open the custom editor shows a dialog saying this is not yet supported.
Device Name: `Razer Huntsman Elite - matrix dimens: 9 22`

It's not entirely clear for me if I can provide any more details. If so, please let me know.

**Comment by z3ntu** [comment] 2020-03-15 14:25
Closing this as duplicate of #67

**Closed by z3ntu** 2020-03-15 14:25 UTC
Labels: customeditor
