### ISSUE TITLE
Please add (fr_FR) keyboard layout for Razer BlackWidow Chroma V2

### ISSUE THREAD

**Issue by Synntix** [z3ntu/RazerGenie#60] opened 2019-08-25 20:35 UTC
Hi, there is a picture of the keyboard for the layout.
![IMG_20190825_223110](https://user-images.githubusercontent.com/36386823/63655450-670e9780-c788-11e9-8443-0af8133378a3.jpg)
(The Razer key in top left is escape)

Thanks !

**Comment by vankasteelj** [comment] 2019-09-27 21:27
#38

**Comment by z3ntu** [comment] 2019-09-28 09:30
Yep, duplicate of #38 and will be fixed with #39

**Closed by z3ntu** 2019-09-28 09:30 UTC
Labels: customeditor
