### ISSUE TITLE
can't install RazerGenie from opensuse repo

### ISSUE THREAD

**Issue by batmanm0b1E** [z3ntu/RazerGenie#43] opened 2019-02-04 23:25 UTC
I can't install razergenie for Debian. opensuse repo gives error for the key. Please help how can i install

**Comment by z3ntu** [comment] 2019-02-06 08:14
What's the error?

**Comment by batmanm0b1E** [comment] 2019-02-06 22:06
W: GPG error: http://download.opensuse.org/repositories/hardware:/razer/Debian_9.0  Release: The following signatures were invalid: EXPKEYSIG 062F9FD4D6D11CE4 hardware OBS Project <hardware@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/hardware:/razer/Debian_9.0  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@scntist:/home/mad# apt-get install razergenie
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package razergenie

**Comment by batmanm0b1E** [comment] 2019-02-06 22:45
Well i complied it. Like mentioned

 DeviceListWidget: Received errored signal!
DeviceListWidget: Reason: "Image download disabled"
DeviceListWidget: Long reason: "Image downloading is disabled. Visit the preferences to enable it."
"mouse"
CURRENT LOCATION:  "0"
Brightness: 100
currDPI: (3200, 3200)
maxDPI: 16000
(1, 15)
mad@scntist:~/Downloads/RazerGenie-0.8.1$

**Comment by z3ntu** [comment] 2019-02-07 04:59
You also have to run the following as **root**:
```
wget -nv https://download.opensuse.org/repositories/hardware:razer/Debian_9.0/Release.key -O Release.key
apt-key add - < Release.key
apt-get update
```

**Comment by kenzierocks** [comment] 2019-02-07 20:21
The release key is expired on my end:
```
$ wget -nv https://download.opensuse.org/repositories/hardware:razer/xUbuntu_18.10/Release.key -O Release.key
$ gpg --show-key Release.key
pub   rsa2048 2014-09-16 [SC] [expired: 2019-02-01]
      E96C496E4E77C159C2FCA053062F9FD4D6D11CE4
uid                      hardware OBS Project <hardware@build.opensuse.org>
```

**Comment by batmanm0b1E** [comment] 2019-02-07 21:52
> You also have to run the following as **root**:
> 
> ```
> wget -nv https://download.opensuse.org/repositories/hardware:razer/Debian_9.0/Release.key -O Release.key
> apt-key add - < Release.key
> apt-get update
> ```

I did that? still error, Also what about this "Image downloading is disabled. Visit the preferences to enable it."

**Comment by z3ntu** [comment] 2019-02-08 13:41
For me it shows
```
pub   rsa2048 2014-09-16 [SC] [expires: 2021-03-28]
      E96C496E4E77C159C2FCA053062F9FD4D6D11CE4
uid                      hardware OBS Project <hardware@build.opensuse.org>
```

The "Image downloading is disabled" message means that you have to click on the button in the bottom left and check the checkbox in the preferences to get fancy device pictures.

**Comment by batmanm0b1E** [comment] 2019-02-08 17:47
SO what would you like me to do.

**Comment by z3ntu** [comment] 2019-02-08 18:04
It seems to be installed for you now so the issue is solved, right?

**Comment by batmanm0b1E** [comment] 2019-02-08 18:58
No it isn't installed. I get that error i showed you. I will try the OBS repo again

**Comment by z3ntu** [comment] 2019-02-08 20:16
Let's mark this as a duplicate of https://github.com/openrazer/openrazer/issues/771 and continue the discussion there.

**Closed by z3ntu** 2019-02-08 20:16 UTC

**Comment by jdotpeg** [comment] 2021-02-09 07:35
Ive got a similar issue but on my fedora 33 system. I get all the way up to the razergenie gui and am greeted with a blue box on the side  with 'Image download disabled'
