### ISSUE TITLE
Two devices of the same model

### ISSUE THREAD

**Issue by dsdante** [z3ntu/RazerGenie#154] opened 2023-03-03 15:52 UTC
1. Run RazerGenie.
2. Connect mouse 1.
3. Wait until it's recognized.
4. Connect mouse 2 of the same model (tested on Abyssus Essential).

Expected result: mouse 2 is recognized and appeared in the device list.

Actual result: mouse 2 is not recognized, and the settings for the mouse 1 don't affect mouse 2.

**Comment by z3ntu** [comment] 2023-03-03 21:34
Does the same behavior also exist when you reopen RazerGenie when both mice are already connected?

**Comment by dsdante** [comment] 2023-03-05 14:32
Yes, RazerGenie only recognizes the mouse I connect first.

**Comment by z3ntu** [comment] 2023-03-06 13:28
Did you check another GUI like polychromatic if that handles it correctly? To be honest I'm not even sure that OpenRazer handles it 100% correct if you have two basically-identical devices since it's normally not really a use case.

**Comment by dsdante** [comment] 2023-03-06 15:02
No, I only tried RazerGenie.

Anyway, it's up to you what to do with this information. :)

**Comment by z3ntu** [comment] 2023-03-06 17:53
![image](https://user-images.githubusercontent.com/3768500/223191001-f90ac701-43c9-4970-ba4a-0ba598a933c8.png)

So with our fake driver setup I cannot reproduce this. Here I have two devices of the same model with just a different serial number and everything works as expected.

Can you run this and send the output? `python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices)"`

**Comment by dsdante** [comment] 2023-03-07 14:36
It returns the serial number of the first connected mouse.
Here are the steps I tried:
1. Connect mouse 1, run the command.
`[<RazerMouse PM1935H08501368>]`
2. Connect mouse 2, run the command.
`[<RazerMouse PM1935H08501368>]`
3. Disconnect mouse 1, run the command.
`[]`
4. Disconnect mouse 2 and connect it again, run the command.
`[<RazerMouse PM2003H08501419>]`

**Comment by z3ntu** [comment] 2023-03-07 19:32
Then the problem is on OpenRazer side at least, and not the GUI. Not sure if that's easier to fix though then :wink: 

When both mice are connected can you post both `ls -al /sys/bus/hid/drivers/razermouse/0*/` and the output of `openrazer-daemon -Fv` (after e.g. `systemctl --user stop openrazer-daemon.service`)

**Comment by dsdante** [comment] 2023-03-12 11:10
Sorry, I've taken mouse 2 to work already; the testing session has ended. :)

**Comment by z3ntu** [comment] 2023-03-12 16:39
Okay, closing this then because in any case it's an OpenRazer issue that can't be solved in this repo.

**Closed by z3ntu** 2023-03-12 16:39 UTC
Labels: openrazer issue
